# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - economic-tracker-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_66ce1007e7d046fe98b91b85070b31bc }}
        password: ${{ secrets.AzureAppService_ContainerPassword_260113f08b97487189e4db2dacde4006 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_66ce1007e7d046fe98b91b85070b31bc }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'economic-tracker-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_978ceef071c146c5aa417d1ef0ad3fb3 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_66ce1007e7d046fe98b91b85070b31bc }}/appsvc/staticsite:${{ github.sha }}'